export const UPDATE_PAGE = 'UPDATE_PAGE';
export const UPDATE_LOADING_STATUS = 'UPDATE_LOADING_STATUS';
export const RESET_GAME = 'RESET_GAME';
export const START_GAME_ASYNC = 'START_GAME_ASYNC';
export const CREATE_WORDS = 'CREATE_WORDS';
export const CREATE_DISPLAY_WORD = 'CREATE_DISPLAY_WORD';
export const UPDATE_CURRENT_WORD = 'UPDATE_CURRENT_WORD';
export const UPDATE_DISPLAY_WORD = 'UPDATE_DISPLAY_WORD';
